In [8]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [4]:
import numpy as np

In [9]:
revenue1 = np.array(revenue)
expenses1 = np.array(expenses)

In [10]:
profit = revenue1 - expenses1

In [10]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [20]:
profitaftertax = profit - (profit * .3)

In [21]:
profitaftertax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [22]:
profitmargin = profitaftertax / revenue1

In [23]:
profitmargin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [20]:
profitaftertaxmean = np.mean(profitaftertax)

In [21]:
profitaftertaxmean

1750.6813333333332

In [23]:
bestmonths = [1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678]

In [24]:
bestmonths1 = np.array(bestmonths)

In [25]:
bestmonths1

array([1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678])

In [26]:
worstmonths = [1337.973, -2595.453, -2040.017, -419.994, -1567.055, 461.72]

In [27]:
worstmonths1 = np.array(worstmonths)

In [28]:
worstmonths1

array([ 1337.973, -2595.453, -2040.017,  -419.994, -1567.055,   461.72 ])

In [29]:
bestmonth = np.max(bestmonths1)

In [30]:
bestmonth

8140.678

In [31]:
worstmonth = np.min(worstmonths1)

In [32]:
worstmonth

-2595.453

In [17]:
profitrounded = np.round(profit)

In [18]:
profitrounded

array([ 2523.,  1911., -3708., -2914.,  -600.,  7265.,  8211.,  3945.,
        3328., -2239.,   660., 11630.])

In [25]:
profitaftertaxrounded = np.round(profitaftertax)

In [26]:
profitaftertaxrounded

array([ 1766.,  1338., -2595., -2040.,  -420.,  5086.,  5747.,  2761.,
        2330., -1567.,   462.,  8141.])

In [37]:
bestmonthsrounded = np.round(bestmonths1)

In [38]:
bestmonthsrounded

array([1766., 5086., 5747., 2761., 2330., 8141.])

In [39]:
worstmonthsrounded = np.round(worstmonths1)

In [40]:
worstmonthsrounded

array([ 1338., -2595., -2040.,  -420., -1567.,   462.])

In [41]:
bestmonthrounded = np.round(bestmonth)

In [42]:
bestmonthrounded

8141.0

In [43]:
worstmonthrounded = np.round(worstmonth)

In [44]:
worstmonthrounded

-2595.0

In [45]:
profitmarginpercent = profitmargin *100

In [46]:
profitmarginpercent

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [47]:
profitmarginpercentrounded = np.round(profitmarginpercent)

In [48]:
profitmarginpercentrounded

array([ 12.,  18., -30., -22.,  -5.,  63.,  50.,  28.,  23., -11.,   4.,
        53.])